# Thanks for Grunt for template of this file!

# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "6.0"
    - nodejs_version: "8.0"
    - nodejs_version: "10.0"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - ps: if ($env:nodejs_version -Eq "8.0") { npm run test }
  - ps: powershell.exe ".\test\full\test.ps1"

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
